version: '3.9'
services:
  tor:
    image: dockage/tor-privoxy:latest
    restart: always
    deploy:
      replicas: 8
  web:
    image: debridmediamanager/debrid-media-manager:latest
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://172.17.0.1:6379
      - GH_PAT=your_github_personal_access_token
    restart: always
    deploy:
      replicas: 8
