version: '3.9'
services:
  debugger:
    image: ubuntu
    volumes:
      - redis_data:/userdata
    entrypoint: ['tail', '-f', '/dev/null']
    deploy:
      replicas: 1

  tor:
    image: dockage/tor-privoxy:latest
    deploy:
      replicas: 64

  web:
    image: debridmediamanager/debrid-media-manager:latest
    ports:
      - 3000:3000
    env_file:
      - .env
      - .env.local
    depends_on:
      - tor
      - redis-sentinel
    deploy:
      replicas: 8
      restart_policy:
        condition: on-failure

  redis-master:
    image: bitnami/redis:latest
    command: redis-server --requirepass dmm123456
    volumes:
      - redis_data:/bitnami/redis/data
    ports:
      - 6379:6379
    deploy:
      replicas: 1

  redis-slave:
    image: bitnami/redis:latest
    command: redis-server --requirepass dmm123456 --slaveof redis-master 6379
    depends_on:
      - redis-master
    volumes:
      - redis_data:/bitnami/redis/data
    deploy:
      replicas: 5

  redis-sentinel:
    image: bitnami/redis-sentinel:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_SENTINEL_CONF=/usr/local/etc/redis-sentinel.conf
    depends_on:
      - redis-master
      - redis-slave
    ports:
      - 26379-26381:26379
    volumes:
      - ./redis-sentinel.conf:/usr/local/etc/redis-sentinel.conf
    deploy:
      replicas: 3

volumes:
  redis_data:
    external: true
