version: '3.9'
services:

  web:
    image: debridmediamanager/debrid-media-manager:latest
    ports:
      - 3000:3000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
