name: Build and Deploy Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read version from package.json
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            debridmediamanager/debrid-media-manager:latest
            debridmediamanager/debrid-media-manager:${{ env.version }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Swarm
        uses: actions-hub/docker/cli@master
        with:
          args: service update --image debridmediamanager/debrid-media-manager:${{ needs.build-image.outputs.version }} dmm_web
        env:
          DOCKER_HOST: tcp://${{ secrets.SWARM_MANAGER_URL }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
