name: Check Package Version

on:
  pull_request:
    branches: [main]

jobs:
  check-package-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check for version update in package.json
      id: check-version
      run: |
        version_base=$(jq -r '.version' $GITHUB_WORKSPACE/${{ github.base_ref }}/package.json)
        version_head=$(jq -r '.version' $GITHUB_WORKSPACE/${{ github.head_ref }}/package.json)
        if [[ "$version_head" != "$version_base" ]]; then
          echo "::set-output name=changed::true"
        else
          echo "::set-output name=changed::false"
        fi
    - name: Fail if version was not updated
      if: steps.check-version.outputs.changed == 'false'
      run: |
        echo "The package.json version was not updated."
        exit 1
    - name: Pass if version was updated
      if: steps.check-version.outputs.changed == 'true'
      run: |
        echo "The package.json version was updated."
